### ISSUE TITLE
How to register new phone number by this script

### ISSUE THREAD

**Issue by bidak** [jonnywilliamson/laragram#1]
i want to register a new number by script and without terminal after After the block of the previous phone number.
is there a way to not block numbers after sending some messages?

**Comment by jonnywilliamson** [comment]
Hi @bidak 

You need to slow or reduce the number of messages you send. I have no data on what number of messages you can send before you get blocked. But I would hazard a guess that if you're spamming a lot of people (and trying to do it in a very quick time-frame) the telegram will have blocking protections in place.

As for the registering a new number - currently outside the scope of this project.

**Comment by billymahmood** [comment]
@bidak @jonnywilliamson 
guys is it possible to setup multiple accounts with this script yet?

**Comment by ghost** [comment]
@billy124 Possible - but 

```
As for the registering a new number - currently outside the scope of this project.
```
