### ISSUE TITLE
Have an error message

### ISSUE THREAD

**Issue by ghost** [jonnywilliamson/laragram#3]
After install and added

``` php
Route::get('/test', function (){
    TG::contactList();
});
```

get an errorpage
![rzmm3rn](https://cloud.githubusercontent.com/assets/737550/10042842/d760ab8c-61f6-11e5-9a67-0ffa5e7f9e56.png)

Laravel 5.1

**Comment by jonnywilliamson** [comment]
Sounds like you haven't got the Telegram CLI up and running properly.

https://github.com/jonnywilliamson/laragram#setup-telegram-cli

Is it only the contactList() or others?

BTW, I'd recommend using telegram bots now and leaving this repo behind.

Check out 
https://github.com/irazasyed/telegram-bot-sdk

https://core.telegram.org/bots

**Comment by ghost** [comment]
Bot Api cant get contactlist from client. 

For all functions getting error page.

I need functionality of this repo. Need help with this. 

P.S. Sory for my bad english - ty for advance.

**Comment by jonnywilliamson** [comment]
Please follow ALL instructions 
https://github.com/jonnywilliamson/laragram#requirements

**Comment by ghost** [comment]
All requirements are added. 
I think problem in added Facades Or Aliases in Service Provider

**Comment by ghost** [comment]
So You can help with this problem?

**Comment by jonnywilliamson** [comment]
Not at the moment with the level of information you have given.
Turn Debug on and post more info.

Can you send an messages? Have you ensured the Telegram CLI service is running

**Comment by ghost** [comment]
Ok. i makin debug log now

2015-09-23 16:58 GMT+03:00 Jonathan notifications@github.com:

> Not at the moment with the level of information you have given.
> Turn Debug on and post more info.
> 
> Can you send an messages? Have you ensured the Telegram CLI service is
> running
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonnywilliamson/laragram/issues/3#issuecomment-142609859
> .

## 

С уважением, Габриелян Д.М.

ICQ:      _3092095_
Skype:  _gt_fios_
