### ISSUE TITLE
A facade root has not been set.

### ISSUE THREAD

**Issue by oppilaakso** [jonnywilliamson/laragram#7]
As title says, I have this problem using Laravel 5.2.

Followed GitHub tutorial, console/terminal Telegram is working fine (I can use commands and send messages using terminal access, SSH).

I have set providers at app.php ("Williamson\Laragram\Laravel\LaragramServiceProvider::class,") and services.php "    'telegram' => [
    'socket' =>'tcp://127.0.0.1:7778'
  ],"

I noticed that no alias has been generated yet (have done composer update and restarted VPS server few times)

**Comment by alexsoft** [comment]
@oppilaakso That's all because TgCommands cannot connect to daemon. Either it is not running, or something else happened to it. Had the same problem

**Comment by jonnywilliamson** [comment]
@oppilaakso Alias issue has been fixed in new v1.

Closing this issue as it appears to be due TG CLI not running...
