### ISSUE TITLE
Deferred ServiceProvider

### ISSUE THREAD

**Issue by alexsoft** [jonnywilliamson/laragram#8]
Could you please make Laragram Service Provider deferred? Because it connects to daemon every single request if I typehint TgCommands in constructor and it's not good.
By some reason, when I am using Facade, it doesn't happen

**Comment by jonnywilliamson** [comment]
Sure, this is a good idea.

**Comment by jonnywilliamson** [comment]
Fixed with 8c4b8977e681bf272ca5f5f79a7f503d50a08229

**Please note this is a breaking change as it appears you cannot register an alias in the service provider IF the service provider is deferred.**

You must now add

``` php
 'TG' => \Williamson\Laragram\Laravel\LaragramFacade::class,
```

to the `config/app.php` alias array manually.

**Comment by alexsoft** [comment]
@jonnywilliamson That's great. Thanks.
But if it is a breaking change, I think you must tag it with major version.

**Comment by jonnywilliamson** [comment]
Sure.

That's why I had bumped the version to 1.0.0 when I made the changes. :)

![image](https://cloud.githubusercontent.com/assets/2513663/15856383/03e978e2-2cad-11e6-8c68-a60e8e2d7f74.png)

**Comment by alexsoft** [comment]
@jonnywilliamson oh, I see. I just thought that you only bumped to 1.0.1. Sorry
